include:
  - project: freedesktop/ci-templates
    ref: 290b79e0e78eab67a83766f4e9691be554fc4afd
    file:
    - templates/ubuntu.yml

stages:
  - container prep
  - build

.common_variables:
  variables:
    FDO_UPSTREAM_REPO: mobile-broadband/libqmi
    FDO_DISTRIBUTION_VERSION: '18.04'
    FDO_DISTRIBUTION_TAG: '2021-07-22.1'
    FDO_DISTRIBUTION_PACKAGES: ca-certificates git gcc autoconf automake libtool
                               libgirepository1.0-dev libglib2.0-dev autopoint
                               gtk-doc-tools libglib2.0-doc libgudev-1.0-dev
                               gobject-introspection valac bash-completion meson
                               ninja-build

build container:
  extends:
  - .fdo.container-build@ubuntu
  - .common_variables
  stage: container prep
  only:
    - master
    - branches
    - merge_requests
    - tags
    - pushes

build-meson-default:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - master
    - merge_requests
    - tags
    - schedules
  script:
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libmbim.git
    - pushd libmbim
    - meson setup build --prefix=/usr -Dgtk_doc=false -Dintrospection=true
    - ninja -C build
    - ninja -C build install
    - popd
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libqrtr-glib.git
    - pushd libqrtr-glib
    - meson setup build --prefix=/usr -Dgtk_doc=false -Dintrospection=true
    - ninja -C build
    - ninja -C build install
    - popd
    - meson setup _debug_build --prefix=/usr -Dwerror=true -Dgtk_doc=false -Dintrospection=true -Dmbim_qmux=true -Dqrtr=true -Drmnet=true
    - ninja -C _debug_build
    - ninja -C _debug_build install
    - ninja -C _debug_build uninstall
    - meson setup _release_build --prefix=/usr --buildtype=release -Dwerror=true -Dgtk_doc=false -Dintrospection=true -Dmbim_qmux=true -Dqrtr=true -Drmnet=true
    - ninja -C _release_build
    - ninja -C _release_build install

build-meson-no-qrtr-no-mbim-no-rmnet-no-introspection:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - master
    - merge_requests
    - tags
    - schedules
  script:
    - meson setup build --prefix=/usr -Dwerror=true -Dgtk_doc=false -Dintrospection=false -Dmbim_qmux=false -Dqrtr=false -Drmnet=false
    - ninja -C build
    - ninja -C build install

build-meson-no-rmnet:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - master
    - merge_requests
    - tags
    - schedules
  script:
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libmbim.git
    - pushd libmbim
    - meson setup build --prefix=/usr -Dgtk_doc=false -Dintrospection=true
    - ninja -C build
    - ninja -C build install
    - popd
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libqrtr-glib.git
    - pushd libqrtr-glib
    - meson setup build --prefix=/usr -Dgtk_doc=false -Dintrospection=true
    - ninja -C build
    - ninja -C build install
    - popd
    - meson setup build --prefix=/usr -Dwerror=true -Dgtk_doc=false -Dintrospection=true -Dmbim_qmux=true -Dqrtr=true -Drmnet=false
    - ninja -C build
    - ninja -C build install

build-meson-no-qrtr:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - master
    - merge_requests
    - tags
    - schedules
  script:
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libmbim.git
    - pushd libmbim
    - meson setup build --prefix=/usr -Dgtk_doc=false -Dintrospection=true
    - ninja -C build
    - ninja -C build install
    - popd
    - meson setup build --prefix=/usr -Dwerror=true -Dgtk_doc=false -Dintrospection=true -Dmbim_qmux=true -Dqrtr=false -Drmnet=true
    - ninja -C build
    - ninja -C build install

build-meson-no-qrtr-no-introspection:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - master
    - merge_requests
    - tags
    - schedules
  script:
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libmbim.git
    - pushd libmbim
    - meson setup build --prefix=/usr -Dgtk_doc=false -Dintrospection=false
    - ninja -C build
    - ninja -C build install
    - popd
    - meson setup build --prefix=/usr -Dwerror=true -Dgtk_doc=false -Dintrospection=false -Dmbim_qmux=true -Dqrtr=false -Drmnet=true
    - ninja -C build
    - ninja -C build install

build-meson-no-mbim:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - master
    - merge_requests
    - tags
    - schedules
  script:
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libqrtr-glib.git
    - pushd libqrtr-glib
    - meson setup build --prefix=/usr -Dgtk_doc=false -Dintrospection=true
    - ninja -C build
    - ninja -C build install
    - popd
    - meson setup build --prefix=/usr -Dwerror=true -Dgtk_doc=false -Dintrospection=true -Dmbim_qmux=false -Dqrtr=true -Drmnet=true
    - ninja -C build
    - ninja -C build install

build-meson-no-mbim-no-introspection:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - master
    - merge_requests
    - tags
    - schedules
  script:
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libqrtr-glib.git
    - pushd libqrtr-glib
    - meson setup build --prefix=/usr -Dgtk_doc=false -Dintrospection=false
    - ninja -C build
    - ninja -C build install
    - popd
    - meson setup build --prefix=/usr -Dwerror=true -Dgtk_doc=false -Dintrospection=false -Dmbim_qmux=false -Dqrtr=true -Drmnet=true
    - ninja -C build
    - ninja -C build install

build-meson-collection-minimal:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - master
    - merge_requests
    - tags
    - schedules
  script:
    - meson setup build --prefix=/usr -Dwerror=true -Dgtk_doc=false -Dintrospection=false -Dmbim_qmux=false -Dqrtr=false -Drmnet=false -Dcollection=minimal -Dfirmware_update=false
    - ninja -C build
    - ninja -C build install

build-meson-collection-basic:
  stage: build
  extends:
  - .fdo.distribution-image@ubuntu
  - .common_variables
  only:
    - master
    - merge_requests
    - tags
    - schedules
  script:
    - meson setup build --prefix=/usr -Dwerror=true -Dgtk_doc=false -Dintrospection=false -Dmbim_qmux=false -Dqrtr=false -Drmnet=false -Dcollection=basic
    - ninja -C build
    - ninja -C build install
