image: gcc

stages:
  - test

before_script:
  - apt update && apt -y install autoconf automake libtool libgudev-1.0-dev autoconf-archive

test-no-deprecated:
  stage: test
  script:
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr CFLAGS="-DQMI_DISABLE_DEPRECATED"
    - make
    - make check
    - make install

test-no-mbim-no-qrtr:
  stage: test
  script:
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr --disable-mbim-qmux --disable-qrtr
    - make
    - make check
    - make install

test-no-mbim:
  stage: test
  script:
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr --disable-mbim-qmux --enable-qrtr
    - make
    - make check
    - make install

test-no-qrtr:
  stage: test
  script:
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libmbim.git
    - pushd libmbim
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr
    - make
    - make install
    - popd
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr --enable-mbim-qmux --disable-qrtr
    - make
    - make check
    - make install

test-collection-minimal:
  stage: test
  script:
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr --disable-mbim-qmux --disable-qrtr --disable-firmware-update --enable-collection=minimal
    - make
    - make check
    - make install

test-collection-basic:
  stage: test
  script:
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr --disable-mbim-qmux --disable-qrtr --enable-collection=basic
    - make
    - make check
    - make install

test-clean-distclean:
  stage: test
  script:
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr
    - make
    - make clean
    - make
    - make distclean
    - ./configure --prefix=/usr
    - make

test-default:
  stage: test
  script:
    - apt -y install gtk-doc-tools libglib2.0-doc gobject-introspection libgirepository1.0-dev
    - git clone --depth 1 https://gitlab.freedesktop.org/mobile-broadband/libmbim.git
    - pushd libmbim
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr
    - make
    - make install
    - popd
    - NOCONFIGURE=1 ./autogen.sh
    - ./configure --prefix=/usr --enable-gtk-doc --enable-mbim-qmux --enable-qrtr --enable-introspection
    - make
    - make check
    - make install
    - make distcheck
    - sha256sum $CI_PROJECT_NAME-*.tar.xz | awk '{print $1;}' > pkg_hash.txt
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"
    paths:
      - /builds/$CI_PROJECT_ROOT_NAMESPACE/$CI_PROJECT_NAME/$CI_PROJECT_NAME-*.tar.xz
      - /builds/$CI_PROJECT_ROOT_NAMESPACE/$CI_PROJECT_NAME/pkg_hash.txt
    expire_in: 2 days
